#!/bin/sh

# Update requirements.in and dev-requirements.in with your new dependencies
# then run this script

set -e

HEADER='# File generated by ./tools/refreeze-requirements.sh\n\n'

rm -rf venv
python3 -m venv venv

./venv/bin/pip install -r requirements.in
printf "# Used by the debian package. Pinned versions for reproducible builds.\n" > requirements.txt
printf "$HEADER" >> requirements.txt
./venv/bin/pip freeze | grep -Ev '^-' >> requirements.txt

./venv/bin/pip install -r dev-requirements.in
printf "$HEADER" > dev-requirements.txt
./venv/bin/pip freeze | grep -Ev '^-' >> dev-requirements.txt
